name: "Deploy to umich AFS"
description: "Publish a webpage from on a GitHub repository"
author: "dctalbot"
branding:
  icon: "arrow-up"
  color: "blue"
inputs:
  workspace-path:
    description: "Path to deployable directory (no leading slash)"
    required: false
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.workspace-path }}
